### ISSUE TITLE
Add GH Action for phylogenetic workflows

### ISSUE THREAD

**Issue by joverlee521** [nextstrain/avian-flu#60]
_Discussed in [Nextstrain priorities meeting](https://docs.google.com/document/d/1hVJBa3d4SsW-WY5Ag4SYVtQXmwMgcoCwQDUyK_5rRbY/edit#heading=h.ibrhu4cnj7r6)_

It'd be helpful to have the GH Action set up for phylogenetic workflows to easily run them with a click of a button. 
Still unclear whether or not these need to be automatically triggered with ingest, but that can be added in the future. 

### TODOs

- [x] add rule to run `nextstrain remote upload`
- [x] add GH Action workflow to use `pathogen-repo-build` for NCBI build
- [ ] add separate GH Action workflow for fauna build
