### ISSUE TITLE
ingest/ncbi: use new augur curate commands

### ISSUE THREAD

**Issue by joverlee521** [nextstrain/avian-flu#67]
Follow up to https://github.com/nextstrain/ingest/issues/43, https://github.com/nextstrain/ingest/issues/44, and blocked on new Augur release. 

### TODOs

- [ ] update [curate rule](https://github.com/nextstrain/avian-flu/blob/master/ingest/build-configs/ncbi/rules/curate.smk#L47) to use new augur curate commands
- [ ] update [curate-metadata rule](https://github.com/nextstrain/avian-flu/blob/master/ingest/build-configs/ncbi/rules/ingest_andersen_lab.smk#L115) to use new augur curate commands
- [ ] remove ingest/vendored since this repo now has shared/vendored
